### PR TITLE
Fix for game update

### PR DESCRIPTION
**Pull request by developer9998**
From what I've seen it works fine

## VR
image

## PC
image

### CODE REVIEW

**Comment by developer9998** [comment]
Turns out this isn't fully needed actually, you can also turn off this in your BepInEx config:
image

But from what I've tried (I closed the game just a second ago) this version works fine with that config on

**Comment by developer9998** [comment]
Followup to the message above ^

Even with that config on as well, the filtering of the main page is still wonky without the changes
Also one last thing, Room Browser is still built into the release ZIP, so maybe try to remove that sometime soon

**Comment by Graicc** [comment]
Not needed with Utilla 1.6.9

**Comment by developer9998** [comment]
If that the case then shouldn't Utilla also be a dependency on MMM when installing CI?
image

**Comment by developer9998** [comment]
And the format is still broke 

image

**Pull request closed without merging**
